### ISSUE TITLE
Problem with displayUsingLabels()

### ISSUE THREAD

**Issue by fukumori** [epartment/nova-dependency-container#16] opened 2018-09-28 19:43 UTC
When i do:
```php
...
            NovaDependencyContainer::make([
                Select::make('Select', 'select')
                    ->options([
                        'yes' => 'Yes, please',
                        'no' => 'Not',
                    ])
                    ->displayUsingLabels(),
            ])->dependsOn('some_field', 'some_value'),
        ];
```
On details of resource select attribute show the key, not label.

**Comment by JILeXanDR** [comment] 2018-10-08 18:29
The same is when using **displayUsing()**. Callback is never called :(

**Comment by daguilarm** [comment] 2018-12-14 14:21
Same here!

**Comment by rk** [comment] 2019-02-01 19:37
Looks like the issue isn't related to the Vue component, based upon my tinkering. It might be related to the PHP Field though. I think that's because it's actually descended from a Field instead of a Panel. But I can't be 100% sure yet, as I'm pretty new to Nova.

**Comment by wize-wiz** [comment] 2019-09-26 20:59
#68

**Comment by wize-wiz** [comment] 2019-09-27 23:54
Fixed in https://github.com/epartment/nova-dependency-container/commit/dddd8a470d57d0885d6ec2531e6c7cc801d45b58

**Closed by wize-wiz** 2019-09-27 23:54 UTC
Labels: bug, confirmed
