### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by lfukumori** [epartment/nova-dependency-container#15] opened 2018-09-28 18:58 UTC
When i do:
```php
    public function fields(Request $request)
    {
        return [
            ....
            NovaDependencyContainer::make([
                    Text::make('field')
                        ->rules(['required']),
            ])->dependsOn('main_field', 'some_value'),
        ];
    }
```
field is not required.

**Comment by unxsist** [comment] 2018-10-02 10:35
This has been fixed in 1.1.1, thanks to @TheoKouzelis

**Closed by unxsist** 2018-10-02 10:35 UTC

**Comment by janyksteenbeek** [comment] 2018-11-08 11:29
It appears that this is still broken in 1.1.1. Any update?

**Comment by bostjanjanzovnik** [comment] 2018-11-19 12:16
Same problem here. It does not trigger any of validation rules what so ever.

**Comment by webhealer** [comment] 2018-12-07 14:09
Same  for me, it's not apply rules for fields when it's in NovaDependencyContainer.

**Comment by daguilarm** [comment] 2018-12-13 17:42
Same here...

**Comment by webhealer** [comment] 2018-12-21 19:07
The problem is, nova only apply validation rules for the fields which defined in the page. The fields are inside the nova dependency container not counts as an individual field , so that validation rules not apply. 

I found a temporary (but not a clean) solution. If it helps someone, i want to share:

If you add same field with same name at the top of the page, it apply the validation rules. But in that case you want to do that fields as hidden. I found the following component which makes fields "hidden".

https://github.com/MohmmedAshraf/nova-hidden-field

So if you add your fields as hidden at the top of the page, then the laravel nova apply validation for both fields, if the field names are same.

**Comment by webhealer** [comment] 2018-12-24 08:14
I fixed the issue.  Please check this PR https://github.com/epartment/nova-dependency-container/pull/36

**Comment by webhealer** [comment] 2018-12-24 14:59
I worked on this issues and created a PR.  https://github.com/epartment/nova-dependency-container/pull/37

The important thing is, **you need the define rules, depends on the field**, otherwise validator will try to validate all the fields on the page, even if not visible.

So you need to apply depended rules, like the example below:

```
            Select::make('Name format', 'name_format')->options([
                0 => 'First Name',
                1 => 'First Name / Last Name',
                2 => 'Full Name'
            ])->displayUsingLabels(),

        NovaDependencyContainer::make([
                Text::make('First Name', 'first_name')->rules('required_if:name_format,0) 
            ])->dependsOn('name_format', 0),
```

**Comment by diegorodriguezvidal** [comment] 2019-01-15 12:23
Same problem here. Rules are not applied in any field inside NovaDependencyContainer.

**Comment by LevFlavien** [comment] 2019-01-25 09:34
Don't forget to apply the trait `use HasDependencies;` or validation won't apply.

**Comment by TheoKouzelis** [comment] 2019-01-31 10:52
@webhealer PR has fixed another conflict which appeared in later versions on Nova. I have now been able to update to Nova v1.3.1 and this package still works thanks to @webhealer PR. I think it should be merged

**Comment by phuclh** [comment] 2019-03-17 19:20
I already use the trait in the resource, but the validation still doesn't work :(. Any solution for that? Thanks

**Comment by mylsCc** [comment] 2019-09-04 21:16
@LevFlavien is right, rules only work if you use HasDependencies. Tried it myself.

**Comment by Prophe1** [comment] 2020-04-15 08:28
Still doesn't seem to be working

**Comment by LoganTFox** [comment] 2021-03-12 17:49
Same here. Validation not working inside dependency container.

**Comment by ragingdave** [comment] 2021-03-12 17:59
Can you show your resource code to try and replicate the issue, because it does appear to be working correctly from my utilization
