### ISSUE TITLE
Not working on versions (2.0 or 2.0.6)

### ISSUE THREAD

**Issue by aronquiray** [epartment/nova-dependency-container#65] opened 2019-06-21 01:40 UTC
I think this package was not working with the latest versions of Nova? 
I currently switched to the latest 2.0.6 (and wasn't doing anything at all)

**Comment by bsormagec** [comment] 2019-06-21 12:10
working after publish nova-resources

**Comment by colemvn** [comment] 2019-06-28 15:38
I was able to install it, but the conditions do not work.

Fields are showing up, etc. Problem is mainly with the conditional fields not showing up.

use Epartment\NovaDependencyContainer\HasDependencies;
use Epartment\NovaDependencyContainer\NovaDependencyContainer;

Are added.

**Comment by colemvn** [comment] 2019-06-28 20:07
Hi!
I got the demo working with the latest and _freshest_ install of Nova.

Look into this: https://github.com/epartment/nova-dependency-container/issues/48

I've been working on my project ever since and it's working perfectly...care to go deeper in details?

**Comment by josespinal** [comment] 2019-07-08 22:46
@colemvn Did it work when Editing?

**Comment by colemvn** [comment] 2019-07-09 00:02
> @colemvn Did it work when Editing?

Yes! I've been using the package since my comment and I haven't met any other problems. Did you look into the issue I shared?

**Comment by josespinal** [comment] 2019-07-09 23:20
Yes! Saw it. The thing is the initial state of the form is all fields with dependencies are hidden. Trying to find out where's the catch.

**Comment by colemvn** [comment] 2019-07-09 23:23
> Yes! Saw it. The thing is the initial state of the form is all fields with dependencies are hidden. Trying to find out where's the catch.

Well in the example is clearly the type for the number.

Maybe they changed how they manage it? Sadly i'm not advanced enough in Nova or this Package to assist you.

**Comment by wize-wiz** [comment] 2019-09-26 08:21
Closing this issue, don't have a clue what the problem is. Open a new issue if I missed anything.

**Closed by wize-wiz** 2019-09-26 08:21 UTC
