### ISSUE TITLE
BelongsTo field in DependencyContainer throws exception

### ISSUE THREAD

**Issue by michielkempen** [epartment/nova-dependency-container#6] opened 2018-09-14 21:33 UTC
When adding a BelongsTo field to a DependencyContainer, Laravel Nova throws a `Trying to get property 'resourceClass' of non-object` exception.

I'm running version 1.0.2 of the package, with these fields in my resource:

```php
Select::make('Type')->options([
   'internal' => 'Internal link',
   'external' => 'External link',
]),


NovaDependencyContainer::make('Dependent settings', [

   Url::make('Link'),

])->dependsOn('type', 'external')->onlyOnForms(),


NovaDependencyContainer::make('Dependent settings', [

   BelongsTo::make('Page', 'page', PageResource::class),

])->dependsOn('type', 'internal')->onlyOnForms(),
```

**Comment by unxsist** [comment] 2018-09-14 22:28
I've just tagged 1.0.3. It adds a `ResourceWithDependencies` class which enables the resolving of relationship fields in dependency containers. If you want to specify any relationship field in a container, you have to extend your resource to use the `ResourceWithDependencies` class. See the README for details!

**Comment by michielkempen** [comment] 2018-09-14 23:14
This fix introduces two new issues:
1. The new `ResourceWithDependencies` uses `App\Nova\Resource` as its parent class. However, when you change the path of the Resource class, as many developers will, the `ResourceWithDependencies` will cause `Class 'App\\Nova\\Resource' not found` exceptions. Using a trait instead of a parent class might solve this problem.
2. The `availableFields` method in the `ResourceWithDependencies` class appends the fields of all the dependency containers to the end of the form. As you can see in the screenshot below, the `link` field is shown twice, and the `page` field should only be visible when the selected type is `internal`.

![screen shot 2018-09-15 at 00 56 19](https://user-images.githubusercontent.com/14795113/45578498-448ab380-b882-11e8-9701-fd807365a0d1.png)

**Comment by unxsist** [comment] 2018-09-15 08:06
Ah, it think it was too late for me working on these fixes. I’ll dive in deeper later today 👍🏻

**Comment by michielkempen** [comment] 2018-09-16 00:07
After a few hours of tinkering about how to tackle these problems, I've come up with a solution.

In short:
1. ✅ Any kind of default Nova field can now be used inside the `NovaDependencyContainer`, including `BelongsTo` fields.
2. ✅ I replaced the `ResourceWithDependencies` class with a `HasDependencies` trait.
3. ✅ I added a `DetailField.vue` component. This allows you to display the fields inside a `NovaDependencyContainer` on the detail page of your resource.
4. ❌ The support of 3rd party fields wasn't stable so I dropped it for now, just to make things a little cleaner. Of course, we can add this back later on.

Since I changed quite some code in [my fork](https://github.com/michielkempen/nova-dependency-container), I didn't made a pull request yet. If you're open for these kind of changes, I will be happy to contribute to your package, otherwise, I will maintain this fork myself, since it currently answers all my needs.

**Comment by unxsist** [comment] 2018-09-16 13:02
@michielkempen Wow! That sounds great, I’m open to any pull requests which optimizes this package any further!

We’ll have to take a look at 3rd party support, nut it’s not a main concern.

I’m looking forward to your pull request!

**Comment by unxsist** [comment] 2018-09-17 06:47
Thanks @michielkempen!

**Closed by unxsist** 2018-09-17 06:47 UTC

**Comment by niladam** [comment] 2018-11-08 10:28
Sorry for posting here since the issue is closed but I think we should have the means to be able to depend on different components.

I'm using this with a custom component (for example nestedform) and nothing happens when i change value..

**Comment by dalmarcolucas** [comment] 2019-11-29 18:56
@niladam To solve this I did the following:

in file **nova\src\Fields\FieldCollection.php** add the method **findFieldRecusive**, that search the field recursively inside the nova-dependency-container "child" fields :

` public function findFieldRecusive($attribute)
    {
        foreach ($this as $field){

            if(isset($field->attribute) && $field->attribute == $attribute)
                return $field;

            if($field->component && $field->component == 'nova-dependency-container'){
                $childField = (new FieldCollection(array_values($field->meta['fields'])))
                    ->findFieldRecusive($attribute);

                if(isset($childField) && isset($childField->attribute) &&  $childField->attribute == $attribute)
                    return $childField;
            }
        }

        return null;
    }`

and in the file **nova\src\Http\Controllers\AssociatableController.php** call the new method instead the firstWhere:

`  $field = $request->newResource()
                    ->availableFields($request)
                    ->firstWhere('attribute', $request->field);
                    ->findFieldRecusive($request->field);`
