### ISSUE TITLE
When updating doesn't show values / conflict with Flexible?

### ISSUE THREAD

**Issue by Nembie** [epartment/nova-dependency-container#147] opened 2021-01-19 10:46 UTC
I have a problem with this package, i don't know if i'm doing something wrong but when i create a resource this works great, when I update a resource the value of the options doesn't show and if I save resource i lost the data.

I use this package with [Flexible](https://github.com/whitecube/nova-flexible-content)

```
Flexible::make(__('Custom fields'))
    ->addLayout(__('New field'), 'text', [
        Text::make(__('Title')),
        Select::make(__('Value type'))
            ->options([
                'text' => 'Text label',
                'select' => 'Select label',
            ])->displayUsingLabels(),
            NovaDependencyContainer::make([
                Flexible::make(__('Options'))
                    ->addLayout(__('New option'), 'text', [
                        Text::make(__('Option value')),
                    ])
            ])
            ->dependsOn('type', 'select'),
    ]),
```

**Comment by harmenjanssen** [comment] 2021-02-16 13:38
I can confirm these packages don't go well together.
If you flip it, and wrap the `Flexible` field inside a `NovaDependencyContainer`, saving is prohibited due to an exception saying "inUseKey called on null".

```
NovaDependencyContainer::make([
  Flexible::make('Foo', 'content')
    ->fullWidth()
    ->addLayout(Foo::class)
    ->limit(1),
])->dependsOn('type', 'foo'),
```

Of course, the question remains if this is a problem with the Flexible package or the NovaDependencyContainer package.

**Comment by ragingdave** [comment] 2021-02-17 02:34
If I had to guess, and this is just a guess, but I'm guessing that something about how this and Flexible are handling child fields on resolve are probably different which is causing the various issues. If someone can put together a PR to address it that'd be great. Unfortunately, I don't have a need for Flexible, so I can't exactly be much help here.

I would have one suggestion though, in the original example, if you don't put Flexible inside the Dependency container, but just put the Text field that you want there might work. It seems from their docs, you wouldn't be nesting Flexible inside Flexible layouts, but I could be wrong.

I'm going to close this to keep the issues clean as this seems heavily dependent on Flexible functionality as they seem to see the layouts as a collection of fields, and if they store values the same way that Nova does, there should be no issue.

**Closed by ragingdave** 2021-02-17 02:34 UTC

**Comment by harmenjanssen** [comment] 2021-02-17 05:55
I actually fixed my issue with [this PR](https://github.com/whitecube/nova-flexible-content/pull/259) on the Flexible repo. 

So for future adventurers: I'm not sure about wrapping `Flexible` _around_ `NovaDependencyContainer`, but wrapping `NovaDependencyContainer` around `Flexible` is definitely possible with the latest versions of these packages. 👍

**Comment by Nembie** [comment] 2021-02-17 15:32
Thanks @harmenjanssen, 
I'll try asap, I had to redesign the part and remove some features, I hope this will help me.

@ragingdave unfortunately what I needed is that the fields were dynamic but your idea is very good.

Thank you both, so much.
