### ISSUE TITLE
Causes failure for Maatwebsite/Laravel-Nova-Excel package

### ISSUE THREAD

**Issue by nysso** [epartment/nova-dependency-container#54] opened 2019-05-08 20:21 UTC
After installing **epartment/nova-dependency-container** another package got affected, the **Maatwebsite/Laravel-Nova-Excel**
and got the **wrong data passed to foreach()** error when exporting excel data using Maatwebsite/Laravel-Nova-Excel

**Comment by wize-wiz** [comment] 2019-09-27 07:30
@nysso I'm having problems too with the this package but I'm unable to reproduce the error. Could you give me a code example where this error occurs?

**Comment by wize-wiz** [comment] 2019-09-28 12:14
I believe this has been fixed in 1.2.2. If there are still problems, then please open a new issue.

**Closed by wize-wiz** 2019-09-28 12:14 UTC
Labels: compatibility, more info required
